Update homestead scripts

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -6,6 +6,7 @@ alias c='clear'
 alias artisan='php artisan'
 alias ls='ls -alh'
 
+alias codecept='vendor/bin/codecept'
 alias phpspec='vendor/bin/phpspec'
 alias phpunit='vendor/bin/phpunit'
 alias serve=serve-laravel
@@ -15,7 +16,7 @@ alias xon='sudo phpenmod -s cli xdebug'
 
 alias nrd="npm run dev"
 alias nrw="npm run watch"
-alias nrww="npm run watch-poll"
+alias nrwp="npm run watch-poll"
 alias nrh="npm run hot"
 alias nrp="npm run production"
 
@@ -36,8 +37,29 @@ function dusk() {
         Xvfb :0 -screen 0 1280x960x24 &
     fi
 
-    php artisan dusk "$@"
+    if [[ $? -eq 0 ]]
+    then
+        php artisan dusk
+    else
+        php artisan dusk --filter "$@"
+    fi
 }
+
+function p() {
+    if [ -f vendor/bin/pest ]; then
+       vendor/bin/pest "$@"
+    else
+       vendor/bin/phpunit "$@"
+    fi
+ }
+
+ function pf() {
+    if [ -f vendor/bin/pest ]; then
+       vendor/bin/pest --filter "$@"
+    else
+       vendor/bin/phpunit --filter "$@"
+    fi
+ }
 
 function php56() {
     sudo update-alternatives --set php /usr/bin/php5.6
@@ -69,12 +91,30 @@ function php73() {
     sudo update-alternatives --set phpize /usr/bin/phpize7.3
 }
 
+function php74() {
+    sudo update-alternatives --set php /usr/bin/php7.4
+    sudo update-alternatives --set php-config /usr/bin/php-config7.4
+    sudo update-alternatives --set phpize /usr/bin/phpize7.4
+}
+
+function php80() {
+    sudo update-alternatives --set php /usr/bin/php8.0
+    sudo update-alternatives --set php-config /usr/bin/php-config8.0
+    sudo update-alternatives --set phpize /usr/bin/phpize8.0
+}
+
+function php81() {
+    sudo update-alternatives --set php /usr/bin/php8.1
+    sudo update-alternatives --set php-config /usr/bin/php-config8.1
+    sudo update-alternatives --set phpize /usr/bin/phpize8.1
+}
+
 function serve-apache() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-apache.sh
-        sudo bash /vagrant/scripts/serve-apache.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/apache.sh
+        sudo bash /vagrant/scripts/site-types/apache.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -86,8 +126,8 @@ function serve-laravel() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-laravel.sh
-        sudo bash /vagrant/scripts/serve-laravel.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/laravel.sh
+        sudo bash /vagrant/scripts/site-types/laravel.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -98,8 +138,8 @@ function serve-laravel() {
 function serve-proxy() {
     if [[ "$1" && "$2" ]]
     then
-        sudo dos2unix /vagrant/scripts/serve-proxy.sh
-        sudo bash /vagrant/scripts/serve-proxy.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/proxy.sh
+        sudo bash /vagrant/scripts/site-types/proxy.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -111,8 +151,8 @@ function serve-silverstripe() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-silverstripe.sh
-        sudo bash /vagrant/scripts/serve-silverstripe.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/silverstripe.sh
+        sudo bash /vagrant/scripts/site-types/silverstripe.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -121,24 +161,24 @@ function serve-silverstripe() {
 }
 
 function serve-spa() {
-  if [[ "$1" && "$2" ]]
-  then
-    sudo bash /vagrant/scripts/create-certificate.sh "$1"
-    sudo dos2unix /vagrant/scripts/serve-spa.sh
-    sudo bash /vagrant/scripts/serve-spa.sh "$1" "$2" 80 443 "${3:-7.1}"
-  else
-    echo "Error: missing required parameters."
-    echo "Usage: "
-    echo "  serve-spa domain path"
-  fi
+    if [[ "$1" && "$2" ]]
+    then
+        sudo bash /vagrant/scripts/create-certificate.sh "$1"
+        sudo dos2unix /vagrant/scripts/site-types/spa.sh
+        sudo bash /vagrant/scripts/site-types/spa.sh "$1" "$2" 80 443 "${3:-8.1}"
+    else
+        echo "Error: missing required parameters."
+        echo "Usage: "
+        echo "  serve-spa domain path"
+    fi
 }
 
 function serve-statamic() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-statamic.sh
-        sudo bash /vagrant/scripts/serve-statamic.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/statamic.sh
+        sudo bash /vagrant/scripts/site-types/statamic.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -150,8 +190,8 @@ function serve-symfony2() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-symfony2.sh
-        sudo bash /vagrant/scripts/serve-symfony2.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/symfony2.sh
+        sudo bash /vagrant/scripts/site-types/symfony2.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -163,8 +203,8 @@ function serve-symfony4() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-symfony4.sh
-        sudo bash /vagrant/scripts/serve-symfony4.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/symfony4.sh
+        sudo bash /vagrant/scripts/site-types/symfony4.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -176,8 +216,8 @@ function serve-pimcore() {
     if [[ "$1" && "$2" ]]
     then
         sudo bash /vagrant/scripts/create-certificate.sh "$1"
-        sudo dos2unix /vagrant/scripts/serve-pimcore.sh
-        sudo bash /vagrant/scripts/serve-pimcore.sh "$1" "$2" 80 443 "${3:-7.1}"
+        sudo dos2unix /vagrant/scripts/site-types/pimcore.sh
+        sudo bash /vagrant/scripts/site-types/pimcore.sh "$1" "$2" 80 443 "${3:-8.1}"
     else
         echo "Error: missing required parameters."
         echo "Usage: "
@@ -268,9 +308,11 @@ function xphp() {
 
     if ! $XDEBUG_ENABLED; then xon; fi
 
+    HOST_IP=$(last --limit=1 | grep -oP '\d+(\.\d+){3}')
+
     php \
-        -dxdebug.remote_host=192.168.10.1 \
-        -dxdebug.remote_autostart=1 \
+        -dxdebug.client_host=${HOST_IP} \
+        -dxdebug.start_with_request=yes \
         "$@"
 
     if ! $XDEBUG_ENABLED; then xoff; fi
